# https://starship.rs/config/#prompt

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$dotnet\
$golang\
$java\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$all[╰─](fg:#9A348E)$character"""

# Change the default prompt characters
[character]
success_symbol = "[❯](fg:#9A348E)"
error_symbol = "[❯](238)"

# Disable the blank line at the start of the prompt
# add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[os.symbols]
Macos = " "
Windows = " "

[directory]
style = "bg:#DA627D fg:#0D2618"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#0D2618"
format = '[ $symbol $branch ]($style)'
truncation_length = 35
truncation_symbol = "…/"

[git_status]
style = "bg:#FCA17D fg:#0D2618"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "[](bg:#FCA17D fg:160)"
# up_to_date = " "
# untracked = " "
ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
# stashed = " "
modified = "[](bg:#FCA17D fg:160)"
staged = '[++\($count\)](bg:#FCA17D fg:#004D20)'
# renamed = " "
# deleted = " "

# [git_status]
# format = '[\($all_status$ahead_behind\)]($style) '
# style = "green"
# conflicted = " "
# up_to_date = " "
# untracked = " "
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# stashed = " "
# modified = " "
# staged = '[++\($count\)](green)'
# renamed = " "
# deleted = " "

[dotnet]
symbol = " "
style = "bg:#86BBD8 fg:#05018D"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#05018D"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#05018D"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#05018D"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#05018D"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format
style = "bg:#33658A"
format = '[  $time ]($style)'
